### PR TITLE
fixed components filenames resolution error in routes due to letter case

### PR DESCRIPTION
**Pull request by kayc33**
The frontend  is now able to compile on my Ubuntu machine.

### CODE REVIEW

**Review by ndianabasi — COMMENTED** [review]
Thank you @kayc33. Please can you lowercase the rest of the file imports and test? I can see some imports in the `routes` file still start with Uppercase.

**Comment by ndianabasi** [comment]
@kayc33, before you go any further, it is wierd that you corrected just two imports fixed the issue for you. There could be another reason for the issue you have. I am no expert in filesystems but I do know that the Linux filesystem is case-sensitive. This means that the name of the file and the import statement should be the same. What you just did basically created discrepancies in the filenames and import statements: `import('../pages/customers/customer.vue')` vs `Customer.vue` as the filename.

Also, there is a convention in Vue to name filenames. So, lowercase names won't be accepted as I'm working with strict recommended from Vue and Eslint. [Single-file component filename casing](https://vuejs.org/v2/style-guide/#Single-file-component-filename-casing-strongly-recommended)

**Comment by kayc33** [comment]
Yes Vue recommends pascal case for single file names..  so instead of fixing from routes, Its only right to rename the files. Sould i effect that?

**Comment by ndianabasi** [comment]
> Yes Vue recommends pascal case for single file names.. so instead of fixing from routes, Its only right to rename the files. Sould i effect that?

I don't think the issue is from the filenames or import statements. Perhaps, it is specific to your own system. I will need some other persons to replicate this issue first.

**Comment by kayc33** [comment]
it is from the filenames. [see here ](https://documentation.n-able.com/remote-management/userguide/Content/Windows_10_Case_sensitive_file.htm).

**Comment by ndianabasi** [comment]
> it is from the filenames. [see here ](https://documentation.n-able.com/remote-management/userguide/Content/Windows_10_Case_sensitive_file.htm).

But, as it is now, the cases in the import statements match the cases of the filenames. Also, why was those two import statements the only source of issue when other import statements still have filename with Pascal case?

**Comment by kayc33** [comment]
Some refactoring needs to be done to some components filenames and routes to make them conventional. 

- frontend/src/pages/customers/index.vue
- frontend/src/pages/invoices/index.vue
- frontend/src/pages/customers/customer.vue
- frontend/src/pages/quotations/index.vue
- frontend/src/pages/receipts/index.vue

**Comment by kayc33** [comment]
Only those two failed because you tried to get them from routes with uppercase meanwhile their filenames are lowercase

**Comment by ndianabasi** [comment]
> Only those two failed because you tried to get them from routes with uppercase meanwhile their filenames are lowercase

Okay. I am reviewing all the filenames right now. I will let know when I'm done.

**Comment by ndianabasi** [comment]
Hello @kayc33. This PR is best suited as an issue. I'm closing this. Please open an issue if you are still have this issue. Thank you.

**Pull request closed without merging**
